import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/Components/Shared/Nav";
import Footer from "@/Components/Shared/Footer";
import UnderNav from "@/Components/Shared/UnderNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Travel-nest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en " className="bg-[#F9F9F9]">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Nav />
        <UnderNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
